### ISSUE TITLE
Cannot create a webdriver

### ISSUE THREAD

**Issue by AquaCobell** [kacperkr90/EsportsCapsuleFarmer#3]
Ive followed the instructions but it looks like the program crashes and tries again but never works. Here are some logs

INFO: 2022/10/04 15:47:19 - Using configuration from: ./config.yaml
INFO: 2022/10/04 15:47:19 - Capsule Farmer is running in container, will read settings from environment variables...
INFO: 2022/10/04 15:47:19 - Config values: [ headless=True, autologin=True, browser=remote, username=*********, password=*********, wait_values_multiplier=1, remoteWdHubUrl=http://firefox:4444/wd/hub, delay=600]
INFO: 2022/10/04 15:47:19 - Waiting for Selenium grid to be ready...
*********************************************************
*          Thank you for using Capsule Farmer!          *
* Please consider supporting League of Poro on YouTube. *
*********************************************************

[Errno 104] Connection reset by peer
CANNOT CREATE A WEBDRIVER!
Press any key to exit...
Traceback (most recent call last):
  File "//./main.py", line 297, in <module>
    driver = createWebdriver(browser, isHeadless and hasAutoLogin)
  File "//./main.py", line 75, in createWebdriver
    wait_for_selenium_grid()
  File "//./main.py", line 59, in wait_for_selenium_grid
    res = request.urlopen(remoteWdHubUrl + "/status")
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//./main.py", line 301, in <module>
    input()
EOFError: EOF when reading a line
INFO: 2022/10/04 15:47:20 - Using configuration from: ./config.yaml
INFO: 2022/10/04 15:47:20 - Capsule Farmer is running in container, will read settings from environment variables...
INFO: 2022/10/04 15:47:20 - Config values: [ headless=True, autologin=True, browser=remote, username=*********, password=*********, wait_values_multiplier=1, remoteWdHubUrl=http://firefox:4444/wd/hub, delay=600]
INFO: 2022/10/04 15:47:20 - Waiting for Selenium grid to be ready...

**Comment by kacperkr90** [comment]
Strange... Do you use default rasbian as OS or something custom? How much memory do you have on your raspberry PI? 
Could you run these commands and paste results here?

`uname -a`
`free -h`
`cat /etc/os-release`
